In [20]:
import os
from datetime import datetime
import requests as r
import numpy as np
import pandas as pd
import geopandas as gp
import io
import matplotlib.pyplot as plt
#from osgeo import gdal
import rasterio as rio
from rasterio.mask import mask
from rasterio.enums import Resampling
from rasterio.shutil import copy
import pyproj
from pyproj import Proj
from shapely.ops import transform
import xarray as xr
#import geoviews as gv
from cartopy import crs
import hvplot.xarray
import holoviews as hv
import boto3
from rasterio.session import AWSSession
import rioxarray as rxr
from rioxarray.merge import merge_arrays
import requests
import h5py
from satpy import Scene
from satpy.readers import hdf5_reader

ImportError: cannot import name 'hdf5_reader' from 'satpy.readers' (c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\satpy\readers\__init__.py)

In [ ]:
# AUTHENTICATION CONFIGURATION
from netrc import netrc
from subprocess import Popen, DEVNULL, STDOUT
from getpass import getpass
from sys import platform

urs = 'urs.earthdata.nasa.gov'    # Earthdata URL to call for authentication
prompts = ['Enter NASA Earthdata Login Username \n(or create an account at urs.earthdata.nasa.gov): ',
           'Enter NASA Earthdata Login Password: ']

# Determine if netrc file exists, and if it includes NASA Earthdata Login Credentials
if 'win' in platform:
    nrc = '_netrc'
else:
    nrc = '.netrc'
try:
    netrcDir = os.path.expanduser(f"~/{nrc}")
    netrc(netrcDir).authenticators(urs)[0]
    del netrcDir

# If not, create a netrc file and prompt user for NASA Earthdata Login Username/Password
except FileNotFoundError:
    homeDir = os.path.expanduser("~")

    # Windows OS won't read the netrc unless this is set
    Popen(f'setx HOME {homeDir}', shell=True, stdout=DEVNULL);

    if nrc == '.netrc':
        Popen(f'touch {homeDir + os.sep}{nrc} | chmod og-rw {homeDir + os.sep}{nrc}', shell=True, stdout=DEVNULL, stderr=STDOUT);

    # Unable to use touch/chmod on Windows OS
    Popen(f'echo machine {urs} >> {homeDir + os.sep}{nrc}', shell=True)
    Popen(f'echo login {getpass(prompt=prompts[0])} >> {homeDir + os.sep}{nrc}', shell=True)
    Popen(f'echo password {getpass(prompt=prompts[1])} >> {homeDir + os.sep}{nrc}', shell=True)
    del homeDir

# Determine OS and edit netrc file if it exists but is not set up for NASA Earthdata Login
except TypeError:
    homeDir = os.path.expanduser("~")
    Popen(f'echo machine {urs} >> {homeDir + os.sep}{nrc}', shell=True)
    Popen(f'echo login {getpass(prompt=prompts[0])} >> {homeDir + os.sep}{nrc}', shell=True)
    Popen(f'echo password {getpass(prompt=prompts[1])} >> {homeDir + os.sep}{nrc}', shell=True)
    del homeDir
del urs, prompts

In [ ]:
# Find last page
base_url = 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/VNP13A2.v002/items/'
collections_response = r.get(base_url, verify=False).json()
total_items = collections_response['numberMatched']
items_returned = collections_response['numberReturned']
last_page = total_items // items_returned
if total_items % items_returned != 0:
    last_page += 1
last_page_url = base_url + f"?page={last_page}"
print(last_page_url)
# https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/VNP13A2.v002/items/?page=11229
last_response = r.get(last_page_url, verify=False).json()

for i in last_response['features']:
    print(i['assets']['browse']['href'])

c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cmr.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/VNP13A2.v002/items/?page=11229


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cmr.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-public/VNP13A2.002/VNP13A2.A2023185.h16v01.002.2023201123309/BROWSE.VNP13A2.A2023185.h16v01.002.2023201123309.1.jpg
https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-public/VNP13A2.002/VNP13A2.A2023185.h15v01.002.2023201122420/BROWSE.VNP13A2.A2023185.h15v01.002.2023201122420.1.jpg
https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-public/VNP13A2.002/VNP13A2.A2023185.h19v01.002.2023201124032/BROWSE.VNP13A2.A2023185.h19v01.002.2023201124032.1.jpg
https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-public/VNP13A2.002/VNP13A2.A2023185.h20v01.002.2023201124919/BROWSE.VNP13A2.A2023185.h20v01.002.2023201124919.1.jpg
https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-public/VNP13A2.002/VNP13A2.A2023185.h11v02.002.2023201114934/BROWSE.VNP13A2.A2023185.h11v02.002.2023201114934.1.jpg


# Testing logic from code that Justin showed

In [49]:
# Perform a search
lp_search = 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'

params = {}

# Set a limit
lim = 100
params['limit'] = lim  # Add in a limit parameter to retrieve 100 items at a time.

# Set the bounding box
field = gp.read_file('Field_Boundary.geojson')
fieldShape = field['geometry'][0]
#bbox = f'{fieldShape.bounds[0]},{fieldShape.bounds[1]},{fieldShape.bounds[2]},{fieldShape.bounds[3]}'    # Defined from ROI bounds
bbox = '-141.00275,41.6751050889,-52.3231986987,83.6751'
print(bbox)
params['bbox'] = bbox 

# Choose your collection
collection = "VNP13A2.v002"
params["collections"] = [collection]

# Set the time
date_time = "2023-07-18T00:00:00Z/2023-08-18T23:59:59Z"
params['datetime'] = date_time

# Make the request
vnp_items = r.post(lp_search, json=params, verify=False).json()['features']
print(len(vnp_items))

item_url = vnp_items[0]['assets']['data']['href']
username = 'infantej2'
password = 'QWEqwe123!@#'

with requests.Session() as session:
    session.auth = (username, password)
    response = session.get(item_url, verify=False)
    print(item_url)
        
    if response.status_code == 200:
        with h5py.File(io.BytesIO(response.content), 'r') as hdf5_file:
            all_h5_objs = []
            hdf5_file.visit(all_h5_objs.append)
            dsList = [str(obj) for obj in all_h5_objs if \
                        isinstance(hdf5_file[obj],h5py.Dataset) and 'GRIDS' in obj]
            info = hdf5_file['HDFEOS INFORMATION']['StructMetadata.0'][()].split()
            metadata_byte2str = [s.decode('utf-8') for s in info]
            ulc = [i for i in metadata_byte2str if 'UpperLeftPointMtrs' in i]
            ulcLon = float(ulc[0].replace('=', ',').replace('(', '') \
                    .replace(')', '').split(',')[1])
            ulcLat = float(ulc[0].replace('=', ',').replace('(', '') \
                    .replace(')', '').split(',')[2])
            geoInfo = (ulcLon, 0, ulcLat, 0)
            print(len(dsList))

            for i, ds in enumerate(dsList):
                dsName = ds.split('/')[-1]
                # Create array and read dimensions            
                dsArray = hdf5_file[ds][()]
                if(len(dsArray.shape) == 2):
                    nRow = dsArray.shape[0]
                    nCol = dsArray.shape[1]
                else:
                    nRow = dsArray.shape[0]
                    nCol = 0
                geoInfo_sd = list(geoInfo)
                print(dsArray)
                
                yRes = -926.6254330555555    
                xRes = 926.6254330555555
                geoInfo_sd.insert(1, xRes)    
                geoInfo_sd.insert(5, yRes) 


-141.00275,41.6751050889,-52.3231986987,83.6751


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cmr.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


29


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h08v04.002.2023201103423/VNP13A2.A2023185.h08v04.002.2023201103423.h5
19
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ...   1727   1750   2238]
 [-15000 -15000 -15000 ...   1875   1696   1675]
 [-15000 -15000 -15000 ...   1703   1671   1964]]
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ...   1644   1583   2005]
 [-15000 -15000 -15000 ...   1718   1544   1519]
 [-15000 -15000 -15000 ...   1555   1553   1748]]
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ...   2886   3018   2916]
 [-15000 -15000 -15000 ...   2996  

# Perform search and read data using satpy

In [16]:
# Perform a search
lp_search = 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'

params = {}

# Set a limit
lim = 100
params['limit'] = lim  # Add in a limit parameter to retrieve 100 items at a time.

# Set the bounding box
field = gp.read_file('Field_Boundary.geojson')
fieldShape = field['geometry'][0]
#bbox = f'{fieldShape.bounds[0]},{fieldShape.bounds[1]},{fieldShape.bounds[2]},{fieldShape.bounds[3]}'    # Defined from ROI bounds
bbox = '-141.00275,41.6751050889,-52.3231986987,83.6751'
print(bbox)
params['bbox'] = bbox 

# Choose your collection
collection = "VNP13A2.v002"
params["collections"] = [collection]

# Set the time
date_time = "2023-07-18T00:00:00Z/2023-08-18T23:59:59Z"
params['datetime'] = date_time

# Make the request
vnp_items = r.post(lp_search, json=params, verify=False).json()['features']
print(len(vnp_items))

# Define an empty list to store the dataset arrays
datasets = []

scene = Scene()

# Iterate through vnp_items and read the datasets
for i, item in enumerate(vnp_items):
    item_url = item['assets']['data']['href']
    username = 'infantej2'
    password = 'QWEqwe123!@#'

    with requests.Session() as session:
        session.auth = (username, password)
        response = session.get(item_url, verify=False)
        print(item_url)
        
        if response.status_code == 200:
            
            hdf5_data = hdf5_reader(response.content)
            scene.add(hdf5_data)

            print(f"Processed item {i}")
        else:
            print(f"Authentication failed or the file is inaccessible for item {i}")

scene.show()
        
'''
# Merge the DataArrays using rioxarray's merge
merged_data_array = merge_arrays(datasets)

# Define the output file
output_file = "mosaic_h5.tif"

# Write the merged dataset to the output file
merged_data_array.rio.to_raster(output_file)
'''
print("Mosaic created successfully.")

-141.00275,41.6751050889,-52.3231986987,83.6751


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cmr.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


29


NameError: name 'Scene' is not defined

# Perform search and read data using h5py and xarray

In [15]:
# Perform a search
lp_search = 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'

params = {}

# Set a limit
lim = 100
params['limit'] = lim  # Add in a limit parameter to retrieve 100 items at a time.

# Set the bounding box
field = gp.read_file('Field_Boundary.geojson')
fieldShape = field['geometry'][0]
#bbox = f'{fieldShape.bounds[0]},{fieldShape.bounds[1]},{fieldShape.bounds[2]},{fieldShape.bounds[3]}'    # Defined from ROI bounds
bbox = '-141.00275,41.6751050889,-52.3231986987,83.6751'
print(bbox)
params['bbox'] = bbox 

# Choose your collection
collection = "VNP13A2.v002"
params["collections"] = [collection]

# Set the time
date_time = "2023-07-18T00:00:00Z/2023-08-18T23:59:59Z"
params['datetime'] = date_time

# Make the request
vnp_items = r.post(lp_search, json=params, verify=False).json()['features']
print(len(vnp_items))

# Define an empty list to store the dataset arrays
datasets = []

# Iterate through vnp_items and read the datasets
for i, item in enumerate(vnp_items):
    item_url = item['assets']['data']['href']
    username = 'infantej2'
    password = 'QWEqwe123!@#'

    with requests.Session() as session:
        session.auth = (username, password)
        response = session.get(item_url, verify=False)
        print(item_url)
        
        if response.status_code == 200:
            # Open the HDF5 file from the response content
            with h5py.File(io.BytesIO(response.content), 'r') as hdf5_file:
                dataset = hdf5_file['HDFEOS/GRIDS/VIIRS_Grid_16Day_VI_1km/Data Fields/1 km 16 days NDVI'][:]

                # Convert the dataset to an xarray DataArray
                data_array = xr.DataArray(dataset, dims=("y", "x"))
                print(dataset)
                print(data_array)

                # Append the DataArray to list
                datasets.append(data_array)

            print(f"Processed item {i}")
        else:
            print(f"Authentication failed or the file is inaccessible for item {i}")
        
'''
# Merge the DataArrays using rioxarray's merge
merged_data_array = merge_arrays(datasets)

# Define the output file
output_file = "mosaic_h5.tif"

# Write the merged dataset to the output file
merged_data_array.rio.to_raster(output_file)
'''
print("Mosaic created successfully.")

-141.00275,41.6751050889,-52.3231986987,83.6751


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cmr.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


29


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h08v04.002.2023201103423/VNP13A2.A2023185.h08v04.002.2023201103423.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ...   2886   3018   2916]
 [-15000 -15000 -15000 ...   2996   2759   2552]
 [-15000 -15000 -15000 ...   3121   2678   2321]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ...,   2886,   3018,   2916],
       [-15000, -15000, -15000, ...,   2996,   2759,   2552],
       [-15000, -15000, -15000, ...,   3121,   2678,   2321]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 0


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h11v04.002.2023201103404/VNP13A2.A2023185.h11v04.002.2023201103404.h5
[[4234 5184 4670 ... 8619 8231 8131]
 [5070 5540 6434 ... 8523 8476 8629]
 [6994 7033 6020 ... 8279 8432 8490]
 ...
 [8613 8467 9008 ... 8245 8057 7746]
 [7868 8374 8954 ... 7109 7503 8355]
 [8521 8714 9033 ... 7940 8481 8601]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[4234, 5184, 4670, ..., 8619, 8231, 8131],
       [5070, 5540, 6434, ..., 8523, 8476, 8629],
       [6994, 7033, 6020, ..., 8279, 8432, 8490],
       ...,
       [8613, 8467, 9008, ..., 8245, 8057, 7746],
       [7868, 8374, 8954, ..., 7109, 7503, 8355],
       [8521, 8714, 9033, ..., 7940, 8481, 8601]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 1


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h10v04.002.2023201103437/VNP13A2.A2023185.h10v04.002.2023201103437.h5
[[8090 8635 8390 ... 3013 3435 3248]
 [8482 8178 8416 ... 3794 4140 4277]
 [8509 8546 8141 ... 4279 6116 7176]
 ...
 [4688 5044 3705 ... 8876 8731 8892]
 [5389 5207 6739 ... 8723 8992 8601]
 [5735 4853 3494 ... 8986 8366 8733]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[8090, 8635, 8390, ..., 3013, 3435, 3248],
       [8482, 8178, 8416, ..., 3794, 4140, 4277],
       [8509, 8546, 8141, ..., 4279, 6116, 7176],
       ...,
       [4688, 5044, 3705, ..., 8876, 8731, 8892],
       [5389, 5207, 6739, ..., 8723, 8992, 8601],
       [5735, 4853, 3494, ..., 8986, 8366, 8733]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 2


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h13v04.002.2023201103448/VNP13A2.A2023185.h13v04.002.2023201103448.h5
[[  7799   7530   7023 ... -15000 -15000 -15000]
 [  7388   6710   6736 ... -15000 -15000 -15000]
 [  6148   6162   6321 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[  7799,   7530,   7023, ..., -15000, -15000, -15000],
       [  7388,   6710,   6736, ..., -15000, -15000, -15000],
       [  6148,   6162,   6321, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 3


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h12v04.002.2023201103408/VNP13A2.A2023185.h12v04.002.2023201103408.h5
[[  8325   8740   8042 ...   7566   7133   7450]
 [  8516   8640   8215 ...   7488   7431   7803]
 [  8688   8451   8649 ...   6927   6987   6193]
 ...
 [  7643   8878   8427 ... -15000 -15000 -15000]
 [  8762   8321   8623 ... -15000 -15000 -15000]
 [  8429   7920   8218 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[  8325,   8740,   8042, ...,   7566,   7133,   7450],
       [  8516,   8640,   8215, ...,   7488,   7431,   7803],
       [  8688,   8451,   8649, ...,   6927,   6987,   6193],
       ...,
       [  7643,   8878,   8427, ..., -15000, -15000, -15000],
       [  8762,   8321,   8623, ..., -15000, -15000, -15000],
       [  8429,   7920,   8218, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 4


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h09v04.002.2023201103403/VNP13A2.A2023185.h09v04.002.2023201103403.h5
[[-15000 -15000 -15000 ...   3542   6516   7074]
 [-15000 -15000 -15000 ...   8019   8451   8365]
 [-15000 -15000 -15000 ...   7845   8053   8428]
 ...
 [  2824   2310   2598 ...   7395   6695   7073]
 [  2337   2304   2184 ...   5752   4596   5947]
 [  2183   2118   2131 ...   4455   6076   5893]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ...,   3542,   6516,   7074],
       [-15000, -15000, -15000, ...,   8019,   8451,   8365],
       [-15000, -15000, -15000, ...,   7845,   8053,   8428],
       ...,
       [  2824,   2310,   2598, ...,   7395,   6695,   7073],
       [  2337,   2304,   2184, ...,   5752,   4596,   5947],
       [  2183,   2118,   2131, ...,   4455,   6076,   5893]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 5


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h08v03.002.2023201105413/VNP13A2.A2023185.h08v03.002.2023201105413.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 6


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h14v04.002.2023201105437/VNP13A2.A2023185.h14v04.002.2023201105437.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 7


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h15v03.002.2023201105448/VNP13A2.A2023185.h15v03.002.2023201105448.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 8


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h14v03.002.2023201105451/VNP13A2.A2023185.h14v03.002.2023201105451.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 9


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h10v03.002.2023201111147/VNP13A2.A2023185.h10v03.002.2023201111147.h5
[[6482 6881 6971 ... 3106 2400 1495]
 [3762 6381 6013 ... 1974  394 3539]
 [5649 5536 8079 ... 8791 8743 8206]
 ...
 [8173 8166 7707 ... 5429 2550 2899]
 [7808 7472 8046 ... 1941 2880 2110]
 [4805 7486 6943 ... 2264 2103 3331]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[6482, 6881, 6971, ..., 3106, 2400, 1495],
       [3762, 6381, 6013, ..., 1974,  394, 3539],
       [5649, 5536, 8079, ..., 8791, 8743, 8206],
       ...,
       [8173, 8166, 7707, ..., 5429, 2550, 2899],
       [7808, 7472, 8046, ..., 1941, 2880, 2110],
       [4805, 7486, 6943, ..., 2264, 2103, 3331]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 10


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h09v03.002.2023201112210/VNP13A2.A2023185.h09v03.002.2023201112210.h5
[[-15000 -15000 -15000 ...   6802   6921   6431]
 [-15000 -15000 -15000 ...   4693   6740   6428]
 [-15000 -15000 -15000 ...   1921   3074   3684]
 ...
 [-15000 -15000 -15000 ...   8120   6793   7263]
 [-15000 -15000 -15000 ...   7240   7455   7933]
 [-15000 -15000 -15000 ...   7830   7444   6832]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ...,   6802,   6921,   6431],
       [-15000, -15000, -15000, ...,   4693,   6740,   6428],
       [-15000, -15000, -15000, ...,   1921,   3074,   3684],
       ...,
       [-15000, -15000, -15000, ...,   8120,   6793,   7263],
       [-15000, -15000, -15000, ...,   7240,   7455,   7933],
       [-15000, -15000, -15000, ...,   7830,   7444,   6832]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 11


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h12v03.002.2023201105447/VNP13A2.A2023185.h12v03.002.2023201105447.h5
[[ 2380  5075  1458 ...  5201  4840  2922]
 [ 2721   983   891 ...  -344 -1404  5859]
 [ 5171  4611  5332 ...  6675  6263  -927]
 ...
 [ 8536  8731  8736 ...  5031  5255  6924]
 [ 8721  8795  8320 ...  5080  4853  6361]
 [ 7702  8569  8447 ...  3736  2719  6247]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[ 2380,  5075,  1458, ...,  5201,  4840,  2922],
       [ 2721,   983,   891, ...,  -344, -1404,  5859],
       [ 5171,  4611,  5332, ...,  6675,  6263,  -927],
       ...,
       [ 8536,  8731,  8736, ...,  5031,  5255,  6924],
       [ 8721,  8795,  8320, ...,  5080,  4853,  6361],
       [ 7702,  8569,  8447, ...,  3736,  2719,  6247]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 12


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h13v03.002.2023201105456/VNP13A2.A2023185.h13v03.002.2023201105456.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000  -1396 ... -15000 -15000 -15000]
 [  -909   -588   -695 ... -15000 -15000 -15000]
 ...
 [  6292   6435   7055 ... -15000 -15000 -15000]
 [  6330   6778   7924 ... -15000 -15000 -15000]
 [  7107   7694   6463 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000,  -1396, ..., -15000, -15000, -15000],
       [  -909,   -588,   -695, ..., -15000, -15000, -15000],
       ...,
       [  6292,   6435,   7055, ..., -15000, -15000, -15000],
       [  6330,   6778,   7924, ..., -15000, -15000, -15000],
       [  7107,   7694,   6463, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 13


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h11v03.002.2023201105408/VNP13A2.A2023185.h11v03.002.2023201105408.h5
[[3367 5039 7561 ... 6440 6190 2687]
 [4739 5828 4861 ... 6003  894 2252]
 [6757 6346 6570 ... 2201 2170 2110]
 ...
 [3014 3493 4157 ... 8357 8452 8542]
 [2936 3955 4054 ... 8233 8386 8680]
 [3447 3580 4247 ... 8516 7952 7606]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[3367, 5039, 7561, ..., 6440, 6190, 2687],
       [4739, 5828, 4861, ..., 6003,  894, 2252],
       [6757, 6346, 6570, ..., 2201, 2170, 2110],
       ...,
       [3014, 3493, 4157, ..., 8357, 8452, 8542],
       [2936, 3955, 4054, ..., 8233, 8386, 8680],
       [3447, 3580, 4247, ..., 8516, 7952, 7606]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 14


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h10v02.002.2023201115854/VNP13A2.A2023185.h10v02.002.2023201115854.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [  8038   7334   7245 ...   8250   6134   4048]
 [  6832   6742   6502 ...   7653    289   1988]
 [  6618   6208   6228 ...   5534   2024   1607]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [  8038,   7334,   7245, ...,   8250,   6134,   4048],
       [  6832,   6742,   6502, ...,   7653,    289,   1988],
       [  6618,   6208,   6228, ...,   5534,   2024,   1607]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 15


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h13v01.002.2023201114911/VNP13A2.A2023185.h13v01.002.2023201114911.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [  5732   5660   5741 ...   2054   2252   2178]
 [  5652   5701   5414 ...   2744   2567   2174]
 [  5574   5361   3577 ...   2139   2390   1993]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [  5732,   5660,   5741, ...,   2054,   2252,   2178],
       [  5652,   5701,   5414, ...,   2744,   2567,   2174],
       [  5574,   5361,   3577, ...,   2139,   2390,   1993]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 16


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h15v02.002.2023201113201/VNP13A2.A2023185.h15v02.002.2023201113201.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 17


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h16v02.002.2023201115923/VNP13A2.A2023185.h16v02.002.2023201115923.h5
[[-15000 -15000 -15000 ...   -502   -566   -295]
 [-15000 -15000 -15000 ...   -467   -700   -688]
 [-15000 -15000 -15000 ...   -360   -680   -598]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ...,   -502,   -566,   -295],
       [-15000, -15000, -15000, ...,   -467,   -700,   -688],
       [-15000, -15000, -15000, ...,   -360,   -680,   -598],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 18


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h13v02.002.2023201115845/VNP13A2.A2023185.h13v02.002.2023201115845.h5
[[  2527   2028   2220 ...   2401   2215   1956]
 [  3077   4995   5871 ...   2117   2302   2267]
 [  5273   4562   6394 ...   2050   2076   2518]
 ...
 [  6260   5599   5152 ... -15000 -15000 -15000]
 [  6117   4900   4003 ... -15000 -15000 -15000]
 [  5536   1407   3333 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[  2527,   2028,   2220, ...,   2401,   2215,   1956],
       [  3077,   4995,   5871, ...,   2117,   2302,   2267],
       [  5273,   4562,   6394, ...,   2050,   2076,   2518],
       ...,
       [  6260,   5599,   5152, ..., -15000, -15000, -15000],
       [  6117,   4900,   4003, ..., -15000, -15000, -15000],
       [  5536,   1407,   3333, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 19


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h14v02.002.2023201114930/VNP13A2.A2023185.h14v02.002.2023201114930.h5
[[  2064   2111   2417 ... -15000 -15000 -15000]
 [  2162   2332   2426 ... -15000 -15000 -15000]
 [  2336   2274   2409 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[  2064,   2111,   2417, ..., -15000, -15000, -15000],
       [  2162,   2332,   2426, ..., -15000, -15000, -15000],
       [  2336,   2274,   2409, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 20


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h12v02.002.2023201115841/VNP13A2.A2023185.h12v02.002.2023201115841.h5
[[-15000 -15000 -15000 ...  -3047  -2344   2683]
 [-15000 -15000 -15000 ...   1689   2512   1956]
 [-15000 -15000 -15000 ...   6223   5370   4791]
 ...
 [  6743   6461   5722 ...   7145   6885   6640]
 [  6114   5602   5190 ...   6979   6529   6152]
 [  6020   5697   4992 ...   6641   6788   5289]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ...,  -3047,  -2344,   2683],
       [-15000, -15000, -15000, ...,   1689,   2512,   1956],
       [-15000, -15000, -15000, ...,   6223,   5370,   4791],
       ...,
       [  6743,   6461,   5722, ...,   7145,   6885,   6640],
       [  6114,   5602,   5190, ...,   6979,   6529,   6152],
       [  6020,   5697,   4992, ...,   6641,   6788,   5289]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 21


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h14v01.002.2023201115919/VNP13A2.A2023185.h14v01.002.2023201115919.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [  2058   1976   1996 ... -15000 -15000 -15000]
 [  1915   1964   2050 ... -15000 -15000 -15000]
 [  1951   1992   2058 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [  2058,   1976,   1996, ..., -15000, -15000, -15000],
       [  1915,   1964,   2050, ..., -15000, -15000, -15000],
       [  1951,   1992,   2058, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 22


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h23v02.002.2023201121038/VNP13A2.A2023185.h23v02.002.2023201121038.h5
Authentication failed or the file is inaccessible for item 23


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h17v01.002.2023201122406/VNP13A2.A2023185.h17v01.002.2023201122406.h5
[[  -846   -829   -839 ... -15000 -15000 -15000]
 [  -889   -867   -872 ... -15000 -15000 -15000]
 [  -834   -836   -845 ... -15000 -15000 -15000]
 ...
 [  -731   -470   -316 ... -15000 -15000 -15000]
 [  -202   -579   -753 ... -15000 -15000 -15000]
 [  -260   -740   -778 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[  -846,   -829,   -839, ..., -15000, -15000, -15000],
       [  -889,   -867,   -872, ..., -15000, -15000, -15000],
       [  -834,   -836,   -845, ..., -15000, -15000, -15000],
       ...,
       [  -731,   -470,   -316, ..., -15000, -15000, -15000],
       [  -202,   -579,   -753, ..., -15000, -15000, -15000],
       [  -260,   -740,   -778, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 24


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h16v01.002.2023201123309/VNP13A2.A2023185.h16v01.002.2023201123309.h5
[[-15000 -15000 -15000 ...  -1039  -1018  -1113]
 [-15000 -15000 -15000 ...  -1044   -959  -1081]
 [-15000 -15000 -15000 ...   -976  -1178   -946]
 ...
 [-15000 -15000 -15000 ...   -525   -368   -495]
 [-15000 -15000 -15000 ...   -252   -539   -233]
 [-15000 -15000 -15000 ...   -624   -680   -253]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ...,  -1039,  -1018,  -1113],
       [-15000, -15000, -15000, ...,  -1044,   -959,  -1081],
       [-15000, -15000, -15000, ...,   -976,  -1178,   -946],
       ...,
       [-15000, -15000, -15000, ...,   -525,   -368,   -495],
       [-15000, -15000, -15000, ...,   -252,   -539,   -233],
       [-15000, -15000, -15000, ...,   -624,   -680,   -253]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 25


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h15v01.002.2023201122420/VNP13A2.A2023185.h15v01.002.2023201122420.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 26


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h20v01.002.2023201124919/VNP13A2.A2023185.h20v01.002.2023201124919.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 27


c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdatacloud.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'urs.earthdata.nasa.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\cinfante\OneDrive - NRCan RNCan\Documents\Greenup\NASA-LPDAAC-Testing\venv\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.lpdaac.earthdata

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/VNP13A2.002/VNP13A2.A2023185.h11v02.002.2023201114934/VNP13A2.A2023185.h11v02.002.2023201114934.h5
[[-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 [-15000 -15000 -15000 ... -15000 -15000 -15000]
 ...
 [  3993   2320   1225 ...   6449   1600   1750]
 [  2026   5086    798 ...   6305   6458   6333]
 [  2380   1372    868 ...   6075   6073   5961]]
<xarray.DataArray (y: 1200, x: 1200)>
array([[-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       [-15000, -15000, -15000, ..., -15000, -15000, -15000],
       ...,
       [  3993,   2320,   1225, ...,   6449,   1600,   1750],
       [  2026,   5086,    798, ...,   6305,   6458,   6333],
       [  2380,   1372,    868, ...,   6075,   6073,   5961]], dtype=int16)
Dimensions without coordinates: y, x
Processed item 28
Mosaic created successfully.


In [ ]:
# Subset by Band

v = vnp_items[20]

evi_band_links = []

# Define which HLS product is being accessed
if v['assets']['browse']['href'].split('/')[4] == 'VNP13A2.v002':
    evi_bands = ['B8A', 'B04', 'B02', 'Fmask'] # NIR RED BLUE Quality for S30
else:
    evi_bands = ['B05', 'B04', 'B02', 'Fmask'] # NIR RED BLUE Quality for L30

# Subset the assets in the item down to only the desired bands
for a in v['assets']: 
    if any(b == a for b in evi_bands):
        evi_band_links.append(v['assets'][a]['href'])
for e in evi_band_links: print(e)

image = io.imread(v['assets']['browse']['href'])  # Load jpg browse image into memory

# Basic plot of the image
plt.figure(figsize=(10,10))              
plt.imshow(image)
plt.show()

del image # Remove the browse image

In [ ]:
# Use vsicurl to load the data directly into memory (be patient, may take a few seconds)
for e in evi_band_links:
    print(e)
    if e.rsplit('.', 2)[-2] == evi_bands[0]:      # NIR index
        nir = rio.open(e)
    elif e.rsplit('.', 2)[-2] == evi_bands[1]:    # red index
        red = rio.open(e)
    elif e.rsplit('.', 2)[-2] == evi_bands[2]:    # blue index
        blue = rio.open(e)
    elif e.rsplit('.', 2)[-2] == evi_bands[3]:    # Fmask index
        fmask = rio.open(e)
print("The COGs have been loaded into memory!")

In [ ]:
geo_CRS = Proj('+proj=longlat +datum=WGS84 +no_defs', preserve_units=True)  # Source coordinate system of the ROI
utm = pyproj.Proj(nir.crs)                                                  # Destination coordinate system
project = pyproj.Transformer.from_proj(geo_CRS, utm)                        # Set up the transformation
fsUTM = transform(project.transform, fieldShape)                            # Apply reprojection